"""
Shared Context and Blackboard Memory for VIGH-02 Multi-Agent Architecture.
Maintains state, task tracking, test results, security audits, code reviews,
and inter-agent message logs across all specialized agent workflows.
"""

import time
import json
import threading
from enum import Enum
from typing import Dict, Any, List, Optional, Union
from pydantic import BaseModel, Field


class AgentRole(str, Enum):
    ORCHESTRATOR = "orchestrator"
    PLANNER = "planner"
    CODER = "coder"
    TESTER = "tester"
    REVIEWER = "reviewer"
    SECURITY = "security"


class TaskStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class TaskItem(BaseModel):
    """Represents a discrete unit of work in the multi-agent plan."""
    id: str
    title: str
    description: str = ""
    assigned_to: AgentRole = AgentRole.CODER
    status: TaskStatus = TaskStatus.PENDING
    result: Optional[str] = None
    target_files: List[str] = Field(default_factory=list)


class ExecutionPlan(BaseModel):
    """Structured plan produced by the Planner Agent."""
    summary: str = ""
    tasks: List[TaskItem] = Field(default_factory=list)
    target_files: List[str] = Field(default_factory=list)
    acceptance_criteria: List[str] = Field(default_factory=list)
    risk_factors: List[str] = Field(default_factory=list)


class TestReport(BaseModel):
    """Execution output and diagnostics from the Tester Agent."""
    success: bool
    command: str = ""
    exit_code: int = 0
    passed_count: int = 0
    failed_count: int = 0
    output: str = ""
    error_traceback: str = ""
    suggestions: List[str] = Field(default_factory=list)
    timestamp: float = Field(default_factory=time.time)


class SecurityFinding(BaseModel):
    """A vulnerability or security concern identified by the Security Agent."""
    severity: str = "MEDIUM"  # CRITICAL, HIGH, MEDIUM, LOW, INFO
    file: str = ""
    line: Optional[int] = None
    issue: str = ""
    snippet: Optional[str] = None
    remediation: str = ""


class SecurityReport(BaseModel):
    """Comprehensive security audit produced by the Security Agent."""
    clean: bool = True
    highest_severity: str = "CLEAN"
    findings: List[SecurityFinding] = Field(default_factory=list)
    summary: str = "No critical security risks identified."
    recommendations: List[str] = Field(default_factory=list)
    timestamp: float = Field(default_factory=time.time)


class ReviewIssue(BaseModel):
    """Code quality, architectural, or edge case issue from Reviewer Agent."""
    severity: str = "INFO"  # BLOCKER, MAJOR, MINOR, INFO
    file: str = ""
    category: str = "code_quality"  # performance, architecture, bug, maintainability
    description: str = ""
    suggestion: str = ""


class ReviewReport(BaseModel):
    """Code quality review generated by the Reviewer Agent."""
    score: int = 10  # 1 to 10 scale
    approved: bool = True
    issues: List[ReviewIssue] = Field(default_factory=list)
    strengths: List[str] = Field(default_factory=list)
    refactor_recommendations: List[str] = Field(default_factory=list)
    timestamp: float = Field(default_factory=time.time)


class AutoFixAttempt(BaseModel):
    """Record of an automated error fixing cycle."""
    iteration: int
    trigger: str  # 'test_failure', 'security_vulnerability', 'review_issue'
    issues_addressed: List[str] = Field(default_factory=list)
    actions_taken: str = ""
    result_success: bool = False
    diff: Optional[str] = None
    timestamp: float = Field(default_factory=time.time)


class AgentMessage(BaseModel):
    """Inter-agent or agent-to-user message in shared memory."""
    timestamp: float = Field(default_factory=time.time)
    role: AgentRole
    sender_name: str
    message_type: str = "thought"  # 'thought', 'plan', 'code', 'tool_call', 'test_report', 'security_report', 'review_report', 'autofix', 'final_response', 'error'
    content: str = ""
    data: Optional[Dict[str, Any]] = None


class SharedContext:
    """
    Centralized blackboard memory shared across all agents in the multi-agent swarm.
    Thread-safe to support concurrent execution of specialized verification agents.
    """

    def __init__(self, user_request: str = "", workspace_root: str = "."):
        self.user_request: str = user_request
        self.workspace_root: str = workspace_root
        self._lock = threading.RLock()

        self.plan: Optional[ExecutionPlan] = None
        self.modified_files: Dict[str, str] = {}
        self.diffs: List[Dict[str, Any]] = []
        self.test_reports: List[TestReport] = []
        self.security_reports: List[SecurityReport] = []
        self.review_reports: List[ReviewReport] = []
        self.autofix_history: List[AutoFixAttempt] = []
        self.messages: List[AgentMessage] = []
        self.blackboard: Dict[str, Any] = {}

    def log_message(
        self,
        role: AgentRole,
        sender_name: str,
        content: str,
        message_type: str = "thought",
        data: Optional[Dict[str, Any]] = None
    ) -> AgentMessage:
        """Appends a message to the shared communication timeline."""
        with self._lock:
            msg = AgentMessage(
                role=role,
                sender_name=sender_name,
                message_type=message_type,
                content=content,
                data=data
            )
            self.messages.append(msg)
            return msg

    def set_plan(self, plan: ExecutionPlan):
        """Updates the active execution plan."""
        with self._lock:
            self.plan = plan
            self.log_message(
                role=AgentRole.PLANNER,
                sender_name="Planner",
                content=f"Execution plan formulated with {len(plan.tasks)} tasks.",
                message_type="plan",
                data=plan.model_dump()
            )

    def update_task_status(self, task_id: str, status: TaskStatus, result: Optional[str] = None):
        """Updates status and result of a specific task."""
        with self._lock:
            if not self.plan:
                return
            for task in self.plan.tasks:
                if task.id == task_id:
                    task.status = status
                    if result is not None:
                        task.result = result
                    break

    def record_diff(self, file_path: str, diff_content: str, description: str = ""):
        """Records a file mutation and diff in shared context."""
        with self._lock:
            self.modified_files[file_path] = description or "Modified by Coder Agent"
            self.diffs.append({
                "path": file_path,
                "diff": diff_content,
                "description": description,
                "timestamp": time.time()
            })

    def add_test_report(self, report: TestReport):
        """Appends a test execution report."""
        with self._lock:
            self.test_reports.append(report)
            status_text = "PASSED" if report.success else "FAILED"
            self.log_message(
                role=AgentRole.TESTER,
                sender_name="Tester",
                content=f"Test Suite [{status_text}]: {report.passed_count} passed, {report.failed_count} failed.",
                message_type="test_report",
                data=report.model_dump()
            )

    def add_security_report(self, report: SecurityReport):
        """Appends a security audit report."""
        with self._lock:
            self.security_reports.append(report)
            self.log_message(
                role=AgentRole.SECURITY,
                sender_name="Security",
                content=f"Security Audit [{report.highest_severity}]: {len(report.findings)} findings.",
                message_type="security_report",
                data=report.model_dump()
            )

    def add_review_report(self, report: ReviewReport):
        """Appends a code review report."""
        with self._lock:
            self.review_reports.append(report)
            app_text = "APPROVED" if report.approved else "CHANGES REQUESTED"
            self.log_message(
                role=AgentRole.REVIEWER,
                sender_name="Reviewer",
                content=f"Code Review [{app_text} - Score {report.score}/10]: {len(report.issues)} items noted.",
                message_type="review_report",
                data=report.model_dump()
            )

    def add_autofix_attempt(self, attempt: AutoFixAttempt):
        """Records an auto-fix cycle."""
        with self._lock:
            self.autofix_history.append(attempt)
            self.log_message(
                role=AgentRole.CODER,
                sender_name="Coder (Auto-Fix)",
                content=f"Auto-fix iteration #{attempt.iteration} ({attempt.trigger}): {'Success' if attempt.result_success else 'Ongoing'}",
                message_type="autofix",
                data=attempt.model_dump()
            )

    def set_blackboard_value(self, key: str, value: Any):
        """Stores arbitrary shared state."""
        with self._lock:
            self.blackboard[key] = value

    def get_blackboard_value(self, key: str, default: Any = None) -> Any:
        with self._lock:
            return self.blackboard.get(key, default)

    def has_critical_issues_or_test_failures(self) -> bool:
        """
        Determines whether auto-fixing is required based on latest test results,
        security findings, and review comments.
        """
        with self._lock:
            # Check latest test report
            if self.test_reports and not self.test_reports[-1].success:
                return True

            # Check latest security report for CRITICAL or HIGH severity
            if self.security_reports:
                latest_sec = self.security_reports[-1]
                for f in latest_sec.findings:
                    if f.severity.upper() in ("CRITICAL", "HIGH"):
                        return True

            # Check latest review for blockers
            if self.review_reports:
                latest_rev = self.review_reports[-1]
                for issue in latest_rev.issues:
                    if issue.severity.upper() in ("BLOCKER", "CRITICAL"):
                        return True

            return False

    def get_auto_fix_diagnostics(self) -> Dict[str, Any]:
        """
        Compiles diagnostics (tracebacks, errors, vulnerability details)
        to feed into the Coder for automatic error resolution.
        """
        with self._lock:
            diagnostics: Dict[str, Any] = {
                "test_errors": [],
                "security_issues": [],
                "review_blockers": []
            }

            if self.test_reports and not self.test_reports[-1].success:
                latest_test = self.test_reports[-1]
                diagnostics["test_errors"].append({
                    "command": latest_test.command,
                    "exit_code": latest_test.exit_code,
                    "output": latest_test.output[-3000:] if latest_test.output else "",
                    "traceback": latest_test.error_traceback[-3000:] if latest_test.error_traceback else "",
                    "suggestions": latest_test.suggestions
                })

            if self.security_reports:
                latest_sec = self.security_reports[-1]
                for f in latest_sec.findings:
                    if f.severity.upper() in ("CRITICAL", "HIGH", "MEDIUM"):
                        diagnostics["security_issues"].append(f.model_dump())

            if self.review_reports:
                latest_rev = self.review_reports[-1]
                for issue in latest_rev.issues:
                    if issue.severity.upper() in ("BLOCKER", "MAJOR"):
                        diagnostics["review_blockers"].append(issue.model_dump())

            return diagnostics

    def get_summary_snapshot(self) -> Dict[str, Any]:
        """Returns a serializable summary dictionary of current shared context."""
        with self._lock:
            return {
                "user_request": self.user_request,
                "workspace_root": self.workspace_root,
                "has_plan": self.plan is not None,
                "total_tasks": len(self.plan.tasks) if self.plan else 0,
                "modified_files": list(self.modified_files.keys()),
                "total_diffs": len(self.diffs),
                "test_runs": len(self.test_reports),
                "latest_test_passed": self.test_reports[-1].success if self.test_reports else None,
                "security_audits": len(self.security_reports),
                "security_clean": self.security_reports[-1].clean if self.security_reports else None,
                "review_score": self.review_reports[-1].score if self.review_reports else None,
                "autofix_iterations": len(self.autofix_history),
                "total_messages": len(self.messages)
            }
